# Generated by Django 3.2.4 on 2021-06-19 04:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reddit', '0002_auto_20210617_0352'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='child_comment_count',
            field=models.IntegerField(default=0),
        ),
    ]
